// <auto-generated />
namespace ANVI_Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialFB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialFB));
        
        string IMigrationMetadata.Id
        {
            get { return "201905240538315_initialFB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
